services:
  - type: worker                 # background worker (no HTTP port required)
    name: InsiderSignalsManual
    env: docker
    plan: starter
    autoDeploy: true
    dockerfilePath: ./Dockerfile

    envVars:
      # --- Required secret (set in Render > Environment) ---
      - key: TELEGRAM_MANUAL_TOKEN
        value: ""                # fill in via Dashboard before starting

      # --- Optional: lock bot to one chat (numeric Telegram chat id) ---
      - key: CHAT_ID
        value: ""

      # --- Timezone & daily report hour ---
      - key: TIMEZONE
        value: Europe/Dublin
      - key: DAILY_REPORT_HOUR
        value: "20"

      # --- Scan cadence & universe size ---
      - key: SCAN_INTERVAL_SECONDS
        value: "30"
      - key: SYMBOLS_PER_SCAN
        value: "20"
      - key: SIGNAL_COOLDOWN_MINUTES
        value: "8"
      - key: MAX_PAIRS
        value: "60"      # raise to 100 later if desired

      # --- Mode & score floor ---
      - key: MODE
        value: STRICT
      - key: SCORE_MIN
        value: "97"

      # --- Exits & trailing (R multiples) ---
      - key: R_TP1
        value: "1.0"
      - key: R_TP2
        value: "2.0"
      - key: R_TP3
        value: "3.0"
      - key: R_SL
        value: "1.1"
      - key: FEE_RATE
        value: "0.001"

      # --- TP ladder config ---
      - key: TP_SPLIT
        value: "30,30,40"
      - key: TP_LEVELS
        value: "3"

      # --- Short trading (paper-only switch) ---
      - key: ENABLE_SHORTS
        value: "0"       # set "1" to enable paper SHORT signals

      # --- SL glitch guard (Update 1) ---
      - key: SL_BAND_PCT
        value: "0.0002"  # 0.02%
      - key: POST_TP_HOLD_MS
        value: "1500"
      - key: MAX_STOP_PCT
        value: "0.20"    # cap SL distance vs entry (20%)
      - key: MAX_GAP_PCT
        value: "0.08"    # log large gaps (8%)

      # --- Paper sizing ---
      - key: POSITION_PCT
        value: "0.05"
      - key: MAX_OPEN_TRADES
        value: "10"
      - key: MIN_USD_PER_TRADE
        value: "10"
      - key: PAPER_START_CASH
        value: "300"
      - key: PAPER_CHECK_SECONDS
        value: "5"       # faster SL/TP checks

      # --- Feature flags (1=on, 0=off) ---
      - key: EDGE
        value: "1"
      - key: CORR
        value: "1"
      - key: REGIME
        value: "1"
      - key: COOLDOWN
        value: "1"
      - key: SESSION
        value: "1"

      # --- Historical quick validator ---
      - key: HIST_LOOKBACK_BARS_5M
        value: "900"
      - key: HIST_MIN_OCCURRENCES
        value: "10"
      - key: HIST_MIN_SUCCESS
        value: "0.55"

      # --- Correlation thresholds ---
      - key: CORR_BLOCK
        value: "0.8"
      - key: CORR_HALF
        value: "0.6"

      # --- Streak/day guard ---
      - key: COOLDOWN_LOSSES
        value: "3"
      - key: COOLDOWN_WINDOW_MIN
        value: "120"
      - key: COOLDOWN_PAUSE_MIN
        value: "60"
      - key: DAY_MAX_DD_PCT
        value: "3.0"
      - key: DAY_LOCK_MIN
        value: "180"

      # --- Request hygiene ---
      - key: RETRY_MAX
        value: "4"
      - key: RETRY_BASE_DELAY
        value: "0.6"
      - key: REQ_JITTER_MIN_MS
        value: "50"
      - key: REQ_JITTER_MAX_MS
        value: "140"

      # --- Quiet session window (local TZ) ---
      - key: SESSION_QUIET_FROM
        value: "2"
      - key: SESSION_QUIET_TO
        value: "5"
