services:
  - type: web
    name: InsiderSignalsManual
    env: docker
    plan: starter
    autoDeploy: true
    dockerfilePath: ./Dockerfile

    envVars:
      # IMPORTANT: Put TELEGRAM_MANUAL_TOKEN ONLY in Render → Environment tab (not here)

      # Strategy defaults (sniper/strict)
      - key: MODE
        value: STRICT
      - key: SCORE_MIN
        value: "97"

      # Timezone & daily report
      - key: TIMEZONE
        value: Europe/Dublin
      - key: DAILY_REPORT_HOUR
        value: "20"

      # Scanner cadence / universe
      - key: SCAN_INTERVAL_SECONDS
        value: "30"
      - key: SYMBOLS_PER_SCAN
        value: "25"
      - key: SIGNAL_COOLDOWN_MINUTES
        value: "8"
      - key: MAX_PAIRS
        value: "50"   # top-50 USD/USDT (sniper scope)

      # Paper engine (starts with €300 / $300)
      - key: TRADE_MODE
        value: PAPER
      - key: PAPER_START_CASH
        value: "300"
      - key: PAPER_CHECK_SECONDS
        value: "15"
      - key: POSITION_PCT
        value: "0.05"        # 5% per trade
      - key: MAX_OPEN_TRADES
        value: "5"           # sniper = 5 (tighter risk)
      - key: MIN_USD_PER_TRADE
        value: "10"
      - key: FEE_RATE
        value: "0.001"       # 0.10% per side
      - key: ALERTS
        value: "1"

      # Filters (strict)
      - key: BREAKOUT_LOOKBACK
        value: "6"
      - key: VOLUME_MULTIPLIER
        value: "1.20"
      - key: RSI_MIN
        value: "35"
      - key: RSI_MAX
        value: "65"
      - key: USE_EMA_CROSS
        value: "1"
      - key: EMA_TOL_PCT
        value: "0.008"
      - key: USE_ADX_FILTER
        value: "1"
      - key: ADX_MIN
        value: "18"
      - key: USE_HTF_FILTER
        value: "1"
      - key: HTF_TOL_PCT
        value: "0.005"
      - key: USE_BTC_BIAS
        value: "1"

      # Exits (R = ATR 5m)
      - key: R_TP1
        value: "1.1"
      - key: R_TP2
        value: "2.2"
      - key: R_SL
        value: "1.1"
      - key: TRAIL_AFTER_TP1
        value: "1"

      # Historical quick validator (ON)
      - key: HIST_LOOKBACK_BARS_5M
        value: "900"     # ~75h
      - key: HIST_MIN_OCCURRENCES
        value: "10"
      - key: HIST_MIN_SUCCESS
        value: "0.55"

      # Correlation + streak guard + session quiet hours
      - key: CORR_BLOCK
        value: "0.8"
      - key: CORR_HALF
        value: "0.6"
      - key: COOLDOWN_LOSSES
        value: "3"
      - key: COOLDOWN_WINDOW_MIN
        value: "120"
      - key: COOLDOWN_PAUSE_MIN
        value: "60"
      - key: SESSION_QUIET_FROM
        value: "2"
      - key: SESSION_QUIET_TO
        value: "5"

      # Keep-alive (your real URL)
      - key: KEEPALIVE_URL
        value: "https://insidersignalsmanual-olo3.onrender.com"
      - key: KEEPALIVE_SECONDS
        value: "240"

      # Retries / jitter
      - key: RETRY_MAX
        value: "4"
      - key: RETRY_BASE_DELAY
        value: "0.6"
      - key: REQ_JITTER_MIN_MS
        value: "50"
      - key: REQ_JITTER_MAX_MS
        value: "140"

