services:
  - type: web
    name: InsiderSignalsManual
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: ./Dockerfile

    envVars:
      # --- Telegram ---
      - key: TELEGRAM_MANUAL_TOKEN
        value: "8411524534:AAHppQZKZBNpSTvvX81s9RAUdlVTCTvaiVc"

      # --- Money-First profile ---
      - key: MODE
        value: STRICT
      - key: SCORE_MIN
        value: "97"

      # Trend & momentum filters
      - key: USE_HTF_FILTER
        value: "1"
      - key: USE_BTC_BIAS
        value: "1"
      - key: USE_ADX_FILTER
        value: "1"
      - key: ADX_MIN
        value: "22"
      - key: BREAKOUT_LOOKBACK
        value: "6"
      - key: VOLUME_MULTIPLIER
        value: "1.35"
      - key: RSI_MIN
        value: "40"
      - key: RSI_MAX
        value: "60"
      - key: USE_EMA_CROSS
        value: "1"
      - key: EMA_TOL_PCT
        value: "0.005"

      # Guards
      - key: MIN_PRICE
        value: "0.01"
      - key: MIN_ATR_PCT
        value: "0.12"
      - key: MAX_ATR_PCT
        value: "2.5"

      # Universe & cadence
      - key: USE_WHITELIST
        value: "1"
      - key: MAX_PAIRS
        value: "20"
      - key: SYMBOLS_PER_SCAN
        value: "10"
      - key: SCAN_INTERVAL_SECONDS
        value: "60"
      - key: SIGNAL_COOLDOWN_MINUTES
        value: "20"

      # Risk & exits
      - key: R_TP1
        value: "1.2"
      - key: R_TP2
        value: "2.5"
      - key: R_SL
        value: "1.2"
      - key: TRAIL_AFTER_TP1
        value: "1"

      # Paper sizing — your request
      - key: POSITION_PCT
        value: "0.05"
      - key: MAX_OPEN_TRADES
        value: "10"
      - key: PAPER_START_CASH
        value: "200"

      # Timezone & daily report
      - key: TIMEZONE
        value: Europe/Dublin
      - key: DAILY_REPORT_HOUR
        value: "20"

      # Keep-alive — YOUR URL (remembered)
      - key: KEEPALIVE_URL
        value: "https://insidersignalsmanual-keen.onrender.com"
      - key: KEEPALIVE_SECONDS
        value: "240"

      # Retries / jitter
      - key: RETRY_MAX
        value: "4"
      - key: RETRY_BASE_DELAY
        value: "0.6"
      - key: REQ_JITTER_MIN_MS
        value: "50"
      - key: REQ_JITTER_MAX_MS
        value: "140"
