services:
  - type: web
    name: InsiderSignalsManual
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: ./Dockerfile

    envVars:
      - key: TELEGRAM_MANUAL_TOKEN
        value: "8411524534:AAHppQZKZBNpSTvvX81s9RAUdlVTCTvaiVc"

      - key: MODE
        value: RELAXED
      - key: SCORE_MIN
        value: "85"

      - key: TIMEZONE
        value: Europe/Dublin
      - key: DAILY_REPORT_HOUR
        value: "20"

      - key: SYMBOLS_PER_SCAN
        value: "60"
      - key: SCAN_INTERVAL_SECONDS
        value: "20"
      - key: SIGNAL_COOLDOWN_MINUTES
        value: "6"
      - key: MAX_PAIRS
        value: "0"

      - key: BREAKOUT_LOOKBACK
        value: "3"
      - key: VOLUME_MULTIPLIER
        value: "1.03"
      - key: RSI_MIN
        value: "20"
      - key: RSI_MAX
        value: "80"
      - key: USE_EMA_CROSS
        value: "1"
      - key: EMA_TOL_PCT
        value: "0.015"

      - key: USE_ADX_FILTER
        value: "1"
      - key: ADX_MIN
        value: "8"
      - key: USE_HTF_FILTER
        value: "0"
      - key: USE_BTC_BIAS
        value: "0"

      - key: R_TP1
        value: "1.1"
      - key: R_TP2
        value: "2.2"
      - key: R_SL
        value: "1.1"
      - key: TRAIL_AFTER_TP1
        value: "1"

      - key: PAPER_START_CASH
        value: "200"
      - key: POSITION_PCT
        value: "0.05"
      - key: MAX_OPEN_TRADES
        value: "10"
      - key: MIN_USD_PER_TRADE
        value: "10"
      - key: FEE_RATE
        value: "0.001"
      - key: PAPER_CHECK_SECONDS
        value: "15"
      - key: ALERTS
        value: "1"

      - key: KEEPALIVE_URL
        value: ""
      - key: KEEPALIVE_SECONDS
        value: "240"

      - key: RETRY_MAX
        value: "4"
      - key: RETRY_BASE_DELAY
        value: "0.6"
      - key: REQ_JITTER_MIN_MS
        value: "50"
      - key: REQ_JITTER_MAX_MS
        value: "140"
