services:
  - type: worker
    name: InsiderSignalsManual
    env: docker
    plan: starter
    autoDeploy: true
    dockerfilePath: ./Dockerfile

    envVars:
      - key: TELEGRAM_MANUAL_TOKEN
        value: ""

      - key: CHAT_ID
        value: ""

      - key: TIMEZONE
        value: Europe/Dublin
      - key: DAILY_REPORT_HOUR
        value: "20"

      - key: SCAN_INTERVAL_SECONDS
        value: "30"
      - key: SYMBOLS_PER_SCAN
        value: "20"
      - key: SIGNAL_COOLDOWN_MINUTES
        value: "8"
      - key: MAX_PAIRS
        value: "60"

      - key: MODE
        value: STRICT
      - key: SCORE_MIN
        value: "97"

      - key: R_TP1
        value: "1.0"
      - key: R_TP2
        value: "2.0"
      - key: R_TP3
        value: "3.0"
      - key: R_SL
        value: "1.1"
      - key: TRAIL_AFTER_TP1
        value: "1"
      - key: FEE_RATE
        value: "0.001"

      - key: POSITION_PCT
        value: "0.05"
      - key: MAX_OPEN_TRADES
        value: "10"
      - key: MIN_USD_PER_TRADE
        value: "10"
      - key: PAPER_START_CASH
        value: "300"
      - key: PAPER_CHECK_SECONDS
        value: "5"

      - key: EDGE
        value: "1"
      - key: CORR
        value: "1"
      - key: REGIME
        value: "1"
      - key: COOLDOWN
        value: "1"
      - key: SESSION
        value: "1"

      # NEW: side toggles (defaults)
      - key: LONGS
        value: "1"
      - key: SHORTS
        value: "0"

      # Optional SL glitch guard knobs (keep defaults unless you know why)
      - key: SL_DEBOUNCE_SEC
        value: "0.35"
      - key: SL_BAND_PCT
        value: "0.0002"
      - key: POST_TP_HOLD_SEC
        value: "1.5"
      - key: MAX_STOP_PCT
        value: "20.0"
      - key: MAX_GAP_PCT
        value: "8.0"
