services:
  - type: worker
    name: InsiderSignalsManual
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    envVars:
      - key: TELEGRAM_MANUAL_TOKEN
        value: "8411524534:AAHm2EYBRLmWKmUGAc5PJ5KH8vXHPGqRjoM"
      - key: TIMEZONE
        value: Europe/Dublin
      - key: DAILY_REPORT_HOUR
        value: "20"
      # Optional: force a chat/channel
      # - key: CHAT_ID
      #   value: "123456789"
