services:
  - type: worker
    name: InsiderSignalsManual
    env: docker
    plan: starter
    autoDeploy: true
    dockerfilePath: ./Dockerfile

    envVars:
      # --- Required secret (set in Render > Environment) ---
      - key: TELEGRAM_MANUAL_TOKEN
        value: ""   # paste in Render dashboard before starting

      # --- Optional: lock bot to one chat (numeric Telegram chat id) ---
      - key: CHAT_ID
        value: ""

      # --- Timezone & daily report hour ---
      - key: TIMEZONE
        value: Europe/Dublin
      - key: DAILY_REPORT_HOUR
        value: "20"

      # --- Scan cadence & universe size ---
      - key: SCAN_INTERVAL_SECONDS
        value: "30"
      - key: SYMBOLS_PER_SCAN
        value: "20"
      - key: SIGNAL_COOLDOWN_MINUTES
        value: "8"
      - key: MAX_PAIRS
        value: "60"   # keep 60 unless you want 100

      # --- Mode & score floor ---
      - key: MODE
        value: STRICT
      - key: SCORE_MIN
        value: "97"

      # --- Exits & trailing ---
      - key: R_TP1
        value: "1.1"
      - key: R_TP2
        value: "2.2"
      - key: R_SL
        value: "1.1"
      - key: TRAIL_AFTER_TP1
        value: "1"
      - key: FEE_RATE
        value: "0.001"

      # --- Paper sizing (you asked: 5% alloc, max 10 open) ---
      - key: POSITION_PCT
        value: "0.05"
      - key: MAX_OPEN_TRADES
        value: "10"
      - key: MIN_USD_PER_TRADE
        value: "10"
      - key: PAPER_START_CASH
        value: "300"

      # --- FAST TP/SL CHECKS (changed to 2 seconds) ---
      - key: PAPER_CHECK_SECONDS
        value: "2"

      # --- Feature flags (1=on, 0=off) ---
      - key: EDGE
        value: "1"
      - key: CORR
        value: "1"
      - key: REGIME
        value: "1"
      - key: COOLDOWN
        value: "1"
      - key: SESSION
        value: "1"

      # --- Historical quick validator ---
      - key: HIST_LOOKBACK_BARS_5M
        value: "900"
      - key: HIST_MIN_OCCURRENCES
        value: "10"
      - key: HIST_MIN_SUCCESS
        value: "0.55"

      # --- Correlation thresholds ---
      - key: CORR_BLOCK
        value: "0.8"
      - key: CORR_HALF
        value: "0.6"

      # --- Streak guard ---
      - key: COOLDOWN_LOSSES
        value: "3"
      - key: COOLDOWN_WINDOW_MIN
        value: "120"
      - key: COOLDOWN_PAUSE_MIN
        value: "60"

      # --- Request hygiene ---
      - key: RETRY_MAX
        value: "4"
      - key: RETRY_BASE_DELAY
        value: "0.6"
      - key: REQ_JITTER_MIN_MS
        value: "50"
      - key: REQ_JITTER_MAX_MS
        value: "140"

      # --- Quiet session window (local TZ) ---
      - key: SESSION_QUIET_FROM
        value: "2"
      - key: SESSION_QUIET_TO
        value: "5"
