services:
  - type: web
    name: InsiderSignalsManual
    env: docker
    plan: starter
    autoDeploy: true
    dockerfilePath: ./Dockerfile

    envVars:
      # (Do NOT hardcode your token here; add it in Render → Environment)
      - key: MODE
        value: STRICT
      - key: SCORE_MIN
        value: "97"

      # Timezone & report
      - key: TIMEZONE
        value: Europe/Dublin
      - key: DAILY_REPORT_HOUR
        value: "20"

      # Scanner cadence
      - key: SCAN_INTERVAL_SECONDS
        value: "30"
      - key: SYMBOLS_PER_SCAN
        value: "25"
      - key: SIGNAL_COOLDOWN_MINUTES
        value: "8"
      - key: MAX_PAIRS
        value: "50"

      # Sizing & risk
      - key: POSITION_PCT
        value: "0.05"
      - key: MAX_OPEN_TRADES
        value: "10"
      - key: MIN_USD_PER_TRADE
        value: "10"
      - key: PAPER_START_CASH
        value: "300"
      - key: R_TP1
        value: "1.1"
      - key: R_TP2
        value: "2.2"
      - key: R_SL
        value: "1.1"
      - key: TRAIL_AFTER_TP1
        value: "1"

      # Historical validator
      - key: HIST_LOOKBACK_BARS_5M
        value: "900"
      - key: HIST_MIN_OCCURRENCES
        value: "10"
      - key: HIST_MIN_SUCCESS
        value: "0.55"

      # Correlation & cooldown
      - key: CORR_BLOCK
        value: "0.8"
      - key: CORR_HALF
        value: "0.6"
      - key: COOLDOWN_LOSSES
        value: "3"
      - key: COOLDOWN_WINDOW_MIN
        value: "120"
      - key: COOLDOWN_PAUSE_MIN
        value: "60"

      # Quiet hours
      - key: SESSION_QUIET_FROM
        value: "2"
      - key: SESSION_QUIET_TO
        value: "5"

      # Retries
      - key: RETRY_MAX
        value: "4"
      - key: RETRY_BASE_DELAY
        value: "0.6"
      - key: REQ_JITTER_MIN_MS
        value: "50"
      - key: REQ_JITTER_MAX_MS
        value: "140"
