services:
  - type: web
    name: InsiderSignalsManual
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    envVars:
      - key: TELEGRAM_MANUAL_TOKEN
        value: "8411524534:AAHppQZKZBNpSTvvX81s9RAUdlVTCTvaiVc"

      - key: MODE
        value: RELAXED

      - key: TIMEZONE
        value: Europe/Dublin
      - key: DAILY_REPORT_HOUR
        value: "20"

      # --- activity & coverage ---
      - key: MIN_SCORE
        value: "80"
      - key: SYMBOLS_PER_SCAN
        value: "120"
      - key: SCAN_INTERVAL_SECONDS
        value: "20"
      - key: SIGNAL_COOLDOWN_MINUTES
        value: "6"
      - key: MAX_PAIRS
        value: "0"

      # --- looser gates ---
      - key: BREAKOUT_LOOKBACK
        value: "2"
      - key: VOLUME_MULTIPLIER
        value: "1.00"
      - key: RSI_MIN
        value: "15"
      - key: RSI_MAX
        value: "85"
      - key: USE_EMA_CROSS
        value: "1"
      - key: EMA_TOL_PCT
        value: "0.02"

      # --- filters ---
      - key: USE_ADX_FILTER
        value: "0"
      - key: ADX_MIN
        value: "10"
      - key: USE_HTF_FILTER
        value: "0"
      - key: USE_BTC_BIAS
        value: "0"

      # --- targets/risk (unchanged) ---
      - key: R_TP1
        value: "1.1"
      - key: R_TP2
        value: "2.2"
      - key: R_SL
        value: "1.1"
      - key: TRAIL_AFTER_TP1
        value: "1"

      # --- keep-alive ---
      - key: KEEPALIVE_URL
        value: "https://insidersignalsmanual-ybsp.onrender.com"
      - key: KEEPALIVE_SECONDS
        value: "240"

      # --- retry/jitter ---
      - key: RETRY_MAX
        value: "4"
      - key: RETRY_BASE_DELAY
        value: "0.6"
      - key: REQ_JITTER_MIN_MS
        value: "50"
      - key: REQ_JITTER_MAX_MS
        value: "140"
