services:
  - type: worker
    name: InsiderSignalsManual
    env: docker
    plan: starter
    autoDeploy: true
    dockerfilePath: ./Dockerfile

    envVars:
      - key: TELEGRAM_MANUAL_TOKEN
        value: ""          # fill in Render dashboard (secret)

      - key: CHAT_ID
        value: ""          # optional lock

      # Timezone & daily report
      - key: TIMEZONE
        value: Europe/Dublin
      - key: DAILY_REPORT_HOUR
        value: "20"

      # Scan cadence & universe
      - key: SCAN_INTERVAL_SECONDS
        value: "30"
      - key: SYMBOLS_PER_SCAN
        value: "20"
      - key: SIGNAL_COOLDOWN_MINUTES
        value: "8"
      - key: MAX_PAIRS
        value: "60"

      # Mode & score floor
      - key: MODE
        value: STRICT
      - key: SCORE_MIN
        value: "97"

      # Exits & trailing
      - key: R_TP1
        value: "1.0"
      - key: R_TP2
        value: "2.0"
      - key: R_TP3
        value: "3.0"
      - key: R_SL
        value: "1.1"
      - key: FEE_RATE
        value: "0.001"
      - key: TP_SPLIT
        value: "40,30,30"
      - key: TP_LEVELS
        value: "3"
      - key: SL_DEBOUNCE_SEC
        value: "0.35"
      - key: SL_BAND_PCT
        value: "0.0002"
      - key: POST_TP_HOLD_SEC
        value: "1.5"
      - key: MAX_STOP_PCT
        value: "20.0"
      - key: MAX_GAP_PCT
        value: "8.0"

      # Paper sizing
      - key: POSITION_PCT
        value: "0.05"
      - key: MAX_OPEN_TRADES
        value: "10"
      - key: MIN_USD_PER_TRADE
        value: "10"
      - key: PAPER_START_CASH
        value: "300"
      - key: PAPER_CHECK_SECONDS
        value: "5"

      # Feature flags
      - key: EDGE
        value: "1"
      - key: CORR
        value: "1"
      - key: REGIME
        value: "1"
      - key: COOLDOWN
        value: "1"
      - key: SESSION
        value: "1"

      # Sides & filters
      - key: LONGS
        value: "1"
      - key: SHORTS
        value: "0"
      - key: CORR_ENABLED
        value: "1"
      - key: CANDLE_FILTER
        value: "0"

      # Historical validator
      - key: HIST_LOOKBACK_BARS_5M
        value: "900"
      - key: HIST_MIN_OCCURRENCES
        value: "10"
      - key: HIST_MIN_SUCCESS
        value: "0.55"

      # Correlation thresholds
      - key: CORR_BLOCK
        value: "0.8"
      - key: CORR_HALF
        value: "0.6"

      # Streak guard
      - key: COOLDOWN_LOSSES
        value: "3"
      - key: COOLDOWN_WINDOW_MIN
        value: "120"
      - key: COOLDOWN_PAUSE_MIN
        value: "60"

      # HTTP hygiene
      - key: RETRY_MAX
        value: "4"
      - key: RETRY_BASE_DELAY
        value: "0.6"
      - key: REQ_JITTER_MIN_MS
        value: "50"
      - key: REQ_JITTER_MAX_MS
        value: "140"

      # Quiet session window
      - key: SESSION_QUIET_FROM
        value: "2"
      - key: SESSION_QUIET_TO
        value: "5"

      # Auto-Tune (OFF by default)
      - key: AUTO_TUNE
        value: "0"
      - key: TUNE_INTERVAL_MIN
        value: "10"
