services:
  - type: web
    name: InsiderSignalsManual
    env: docker
    plan: starter          # paid plan; adjust if you pick another
    autoDeploy: true
    dockerfilePath: ./Dockerfile

    # IMPORTANT: do NOT put your Telegram token here.
    # Add TELEGRAM_MANUAL_TOKEN in Render → Dashboard → InsiderSignalsManual → Environment.
    envVars:
      - key: TIMEZONE
        value: Europe/Dublin
      - key: DAILY_REPORT_HOUR
        value: "20"

      # Universe / cadence
      - key: MAX_PAIRS
        value: "60"
      - key: SCAN_INTERVAL_SECONDS
        value: "30"
      - key: SYMBOLS_PER_SCAN
        value: "20"
      - key: SIGNAL_COOLDOWN_MINUTES
        value: "8"

      # Mode & score
      - key: MODE
        value: STRICT
      - key: SCORE_MIN
        value: "97"

      # Paper sizing
      - key: PAPER_START_CASH
        value: "300"
      - key: POSITION_PCT
        value: "0.05"     # 5%
      - key: MAX_OPEN_TRADES
        value: "10"
      - key: MIN_USD_PER_TRADE
        value: "10"

      # Exits (R = ATR 5m)
      - key: R_TP1
        value: "1.1"
      - key: R_TP2
        value: "2.2"
      - key: R_SL
        value: "1.1"
      - key: TRAIL_AFTER_TP1
        value: "1"

      # Modules (1=ON, 0=OFF)
      - key: EDGE
        value: "1"
      - key: CORR
        value: "1"
      - key: REGIME
        value: "1"
      - key: COOLDOWN
        value: "1"
      - key: SESSION
        value: "1"

      # Historical validator knobs
      - key: HIST_LOOKBACK_BARS_5M
        value: "900"
      - key: HIST_MIN_OCCURRENCES
        value: "10"
      - key: HIST_MIN_SUCCESS
        value: "0.55"

      # Correlation thresholds
      - key: CORR_BLOCK
        value: "0.8"
      - key: CORR_HALF
        value: "0.6"

      # Streak guard
      - key: COOLDOWN_LOSSES
        value: "3"
      - key: COOLDOWN_WINDOW_MIN
        value: "120"
      - key: COOLDOWN_PAUSE_MIN
        value: "60"

      # Retry / jitter
      - key: RETRY_MAX
        value: "4"
      - key: RETRY_BASE_DELAY
        value: "0.6"
      - key: REQ_JITTER_MIN_MS
        value: "50"
      - key: REQ_JITTER_MAX_MS
        value: "140"
