services:
  - type: web
    name: InsiderSignalsManual
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: ./Dockerfile

    envVars:
      # --- required
      - key: TELEGRAM_MANUAL_TOKEN
        # add your token in Render UI (don’t commit secrets to Git)
        sync: false

      # --- core settings (can be changed later with bot commands)
      - key: MODE
        value: STRICT                # RELAXED or STRICT (you can /setmode)
      - key: SCORE_MIN
        value: "90"                  # change live with /setscore 1..100

      # scanning cadence
      - key: SCAN_INTERVAL_SECONDS
        value: "30"
      - key: SYMBOLS_PER_SCAN
        value: "30"
      - key: SIGNAL_COOLDOWN_MINUTES
        value: "8"
      - key: MAX_PAIRS
        value: "20"                  # scan 20 most common symbols per loop

      # risk/sizing (defaults; adjustable in chat)
      - key: POSITION_PCT
        value: "0.05"                # 5% per trade (you asked for this)
      - key: MAX_OPEN_TRADES
        value: "10"                  # you asked for 10

      # exits (R := ATR(5m))
      - key: R_TP1
        value: "1.1"
      - key: R_TP2
        value: "2.2"
      - key: R_SL
        value: "1.1"
      - key: TRAIL_AFTER_TP1
        value: "1"

      # timezone & daily summary
      - key: TIMEZONE
        value: Europe/Dublin
      - key: DAILY_REPORT_HOUR
        value: "20"

      # keep-alive (your REAL URL)
      - key: KEEPALIVE_URL
        value: "https://insidersignalsmanual-olo3.onrender.com"
      - key: KEEPALIVE_SECONDS
        value: "240"

      # paper account & alerts
      - key: PAPER_START_CASH
        value: "200"
      - key: ALERTS
        value: "1"
      - key: PAPER_CHECK_SECONDS
        value: "15"

      # retries / jitter
      - key: RETRY_MAX
        value: "4"
      - key: RETRY_BASE_DELAY
        value: "0.6"
      - key: REQ_JITTER_MIN_MS
        value: "50"
      - key: REQ_JITTER_MAX_MS
        value: "140"
