services:
  - type: web
    name: InsiderSignalsManual
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: ./Dockerfile

    envVars:
      # ---- REQUIRED (replace with your token, no spaces) ----
      - key: TELEGRAM_MANUAL_TOKEN
        value: "8411524534:AAHppQZKZBNpSTvvX81s9RAUdlVTCTvaiVc"
        # Or: fromSecret: TELEGRAM_MANUAL_TOKEN

      # Timezone + daily report hour (local)
      - key: TIMEZONE
        value: Europe/Dublin
      - key: DAILY_REPORT_HOUR
        value: "20"

      # Scanning cadence / rotation
      - key: SCAN_INTERVAL_SECONDS
        value: "45"
      - key: SYMBOLS_PER_SCAN
        value: "18"
      - key: SIGNAL_COOLDOWN_MINUTES
        value: "10"
      - key: MAX_PAIRS
        value: "0"        # 0 = scan all USD/USDT pairs

      # Relaxed entry gates
      - key: BREAKOUT_LOOKBACK
        value: "6"
      - key: VOLUME_MULTIPLIER
        value: "1.1"
      - key: RSI_MIN
        value: "25"
      - key: RSI_MAX
        value: "75"
      - key: USE_EMA_CROSS
        value: "1"
      - key: EMA_TOL_PCT
        value: "0.008"

      # Pro filters
      - key: USE_ADX_FILTER
        value: "1"
      - key: ADX_MIN
        value: "18"
      - key: USE_HTF_FILTER
        value: "1"
      - key: HTF_TOL_PCT
        value: "0.005"
      - key: USE_BTC_BIAS
        value: "1"

      # Risk / exits (R = ATR(5m))
      - key: R_TP1
        value: "1.1"
      - key: R_TP2
        value: "2.2"
      - key: R_SL
        value: "1.1"
      - key: TRAIL_AFTER_TP1
        value: "1"

      # Keep-alive (paste YOUR service URL below)
      - key: KEEPALIVE_URL
        value: "https://insidersignalsmanual-ybsp.onrender.com"
      - key: KEEPALIVE_SECONDS
        value: "240"

      # Robust retries / jitter
      - key: RETRY_MAX
        value: "4"
      - key: RETRY_BASE_DELAY
        value: "0.6"
      - key: REQ_JITTER_MIN_MS
        value: "50"
      - key: REQ_JITTER_MAX_MS
        value: "140"
