services:
  - type: web
    name: InsiderSignalsManual
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: ./Dockerfile

    envVars:
      # REQUIRED — replace with your real token (no spaces)
      - key: TELEGRAM_MANUAL_TOKEN
        value: "8411524534:AAHppQZKZBNpSTvvX81s9RAUdlVTCTvaiVc"

      # label for messages
      - key: MODE
        value: RELAXED

      # timezone & daily report hour
      - key: TIMEZONE
        value: Europe/Dublin
      - key: DAILY_REPORT_HOUR
        value: "20"

      # RELAXED scanning
      - key: SCAN_INTERVAL_SECONDS
        value: "30"
      - key: SYMBOLS_PER_SCAN
        value: "30"
      - key: SIGNAL_COOLDOWN_MINUTES
        value: "8"
      - key: MAX_PAIRS
        value: "0"

      # RELAXED gates
      - key: BREAKOUT_LOOKBACK
        value: "3"
      - key: VOLUME_MULTIPLIER
        value: "1.05"
      - key: RSI_MIN
        value: "20"
      - key: RSI_MAX
        value: "80"
      - key: USE_EMA_CROSS
        value: "1"
      - key: EMA_TOL_PCT
        value: "0.012"

      # Filters (looser)
      - key: USE_ADX_FILTER
        value: "1"
      - key: ADX_MIN
        value: "10"
      - key: USE_HTF_FILTER
        value: "0"
      - key: USE_BTC_BIAS
        value: "0"

      # Risk / exits
      - key: R_TP1
        value: "1.1"
      - key: R_TP2
        value: "2.2"
      - key: R_SL
        value: "1.1"
      - key: TRAIL_AFTER_TP1
        value: "1"

      # Keep-alive (put YOUR service URL here)
      - key: KEEPALIVE_URL
        value: "https://insidersignalsmanual-ybsp.onrender.com"
      - key: KEEPALIVE_SECONDS
        value: "240"

      # Robust retries / jitter
      - key: RETRY_MAX
        value: "4"
      - key: RETRY_BASE_DELAY
        value: "0.6"
      - key: REQ_JITTER_MIN_MS
        value: "50"
      - key: REQ_JITTER_MAX_MS
        value: "140"
