services:
  - type: worker
    name: InsiderSignalsManual
    env: docker
    plan: starter          # you're on paid; starter is fine
    autoDeploy: true
    dockerfilePath: ./Dockerfile

    envVars:
      # --- REQUIRED (set value in Render dashboard before starting) ---
      - key: TELEGRAM_MANUAL_TOKEN
        value: ""

      # --- Optional: lock bot to one Telegram chat id (numeric) ---
      - key: CHAT_ID
        value: ""

      # --- Timezone & reports ---
      - key: TIMEZONE
        value: Europe/Dublin
      - key: DAILY_REPORT_HOUR
        value: "20"

      # --- Scan cadence & universe ---
      - key: SCAN_INTERVAL_SECONDS
        value: "30"
      - key: SYMBOLS_PER_SCAN
        value: "20"
      - key: SIGNAL_COOLDOWN_MINUTES
        value: "8"
      - key: MAX_PAIRS
        value: "60"

      # --- Mode & score ---
      - key: MODE
        value: STRICT
      - key: SCORE_MIN
        value: "97"

      # --- Exits & trailing ---
      - key: R_TP1
        value: "1.1"
      - key: R_TP2
        value: "2.2"
      - key: R_SL
        value: "1.1"
      - key: TRAIL_AFTER_TP1
        value: "1"
      - key: FEE_RATE
        value: "0.001"

      # --- Paper sizing ---
      - key: POSITION_PCT
        value: "0.05"
      - key: MAX_OPEN_TRADES
        value: "10"
      - key: MIN_USD_PER_TRADE
        value: "10"
      - key: PAPER_START_CASH
        value: "300"
      - key: PAPER_CHECK_SECONDS
        value: "15"

      # --- Feature flags (1=on, 0=off) ---
      - key: EDGE
        value: "1"
      - key: CORR
        value: "1"
      - key: REGIME
        value: "1"
      - key: COOLDOWN
        value: "1"
      - key: SESSION
        value: "1"

      # --- Historical quick validator ---
      - key: HIST_LOOKBACK_BARS_5M
        value: "900"
      - key: HIST_MIN_OCCURRENCES
        value: "10"
      - key: HIST_MIN_SUCCESS
        value: "0.55"

      # --- Correlation thresholds ---
      - key: CORR_BLOCK
        value: "0.8"
      - key: CORR_HALF
        value: "0.6"

      # --- Streak guard ---
      - key: COOLDOWN_LOSSES
        value: "3"
      - key: COOLDOWN_WINDOW_MIN
        value: "120"
      - key: COOLDOWN_PAUSE_MIN
        value: "60"

      # --- Request hygiene ---
      - key: RETRY_MAX
        value: "4"
      - key: RETRY_BASE_DELAY
        value: "0.6"
      - key: REQ_JITTER_MIN_MS
        value: "50"
      - key: REQ_JITTER_MAX_MS
        value: "140"

      # --- Quiet session window (local TZ) ---
      - key: SESSION_QUIET_FROM
        value: "2"
      - key: SESSION_QUIET_TO
        value: "5"

      # --- NEW safeguards ---
      - key: ATR_FLOOR_PCT         # min ATR as % of price to prevent crazy SL spans
        value: "0.001"             # = 0.1%
      - key: ALERT_BATCH_SECONDS    # batch Telegram alerts to avoid 429s
        value: "3"
