services:
  - type: worker
    name: insider-manual-bot-v41
    env: python
    buildCommand: ""
    startCommand: "python manual_bot.py"
    plan: starter
    autoDeploy: true
    envVars:
      - key: TELEGRAM_MANUAL_TOKEN
        sync: false           # put your bot token value in the dashboard/Env tab
      - key: TIMEZONE
        value: Europe/Dublin
      - key: DAILY_REPORT_HOUR
        value: "20"

      # Scan cadence & universe
      - key: SCAN_INTERVAL_SECONDS
        value: "30"
      - key: SYMBOLS_PER_SCAN
        value: "20"
      - key: MAX_PAIRS
        value: "60"
      - key: SIGNAL_COOLDOWN_MINUTES
        value: "8"

      # Scoring / modes
      - key: SCORE_MIN
        value: "97"
      - key: MODE
        value: "STRICT"

      # Exits & ladder (R = ATR(5m))
      - key: R_TP1
        value: "1.0"
      - key: R_TP2
        value: "2.0"
      - key: R_TP3
        value: "3.0"
      - key: R_SL
        value: "1.1"
      - key: TP_SPLIT
        value: "40,30,30"
      - key: TP_LEVELS
        value: "3"
      - key: FEE_RATE
        value: "0.001"

      # SL glitch protection
      - key: SL_DEBOUNCE_SEC
        value: "0.35"
      - key: SL_BAND_PCT
        value: "0.0002"
      - key: POST_TP_HOLD_SEC
        value: "1.5"
      - key: MAX_STOP_PCT
        value: "20.0"
      - key: MAX_GAP_PCT
        value: "8.0"

      # Paper sizing (can change at runtime via commands)
      - key: POSITION_PCT
        value: "0.05"
      - key: MAX_OPEN_TRADES
        value: "10"
      - key: MIN_USD_PER_TRADE
        value: "10"
      - key: PAPER_START_CASH
        value: "300"
      - key: PAPER_CHECK_SECONDS
        value: "5"

      # Feature flags (1/0)
      - key: EDGE
        value: "1"
      - key: CORR
        value: "1"
      - key: REGIME
        value: "1"
      - key: COOLDOWN
        value: "1"
      - key: SESSION
        value: "1"

      # Side toggles (can also flip by commands)
      - key: LONGS
        value: "1"
      - key: SHORTS
        value: "0"

      # Correlation & candles (togglable via commands)
      - key: CORR_ENABLED
        value: "1"
      - key: CANDLE_FILTER
        value: "0"

      # Auto-Tune (OFF by default; turn on with /autotune 1)
      - key: AUTO_TUNE
        value: "0"
      - key: TUNE_INTERVAL_MIN
        value: "10"

      # Quiet session window (02–05 local time)
      - key: SESSION_QUIET_FROM
        value: "2"
      - key: SESSION_QUIET_TO
        value: "5"
