services:
  - type: worker
    name: InsiderSignalsManual
    env: docker
    plan: starter
    autoDeploy: true
    dockerfilePath: ./Dockerfile

    envVars:
      - key: TELEGRAM_MANUAL_TOKEN
        value: ""                 # set this in Render Dashboard (Environment)

      - key: TIMEZONE
        value: Europe/Dublin
      - key: DAILY_REPORT_HOUR
        value: "20"

      # scan cadence & universe
      - key: SCAN_INTERVAL_SECONDS
        value: "30"
      - key: SYMBOLS_PER_SCAN
        value: "20"
      - key: SIGNAL_COOLDOWN_MINUTES
        value: "8"
      - key: MAX_PAIRS
        value: "60"

      # mode & score
      - key: MODE
        value: STRICT
      - key: SCORE_MIN
        value: "97"

      # exits & TPs
      - key: R_TP1
        value: "1.0"
      - key: R_TP2
        value: "2.0"
      - key: R_TP3
        value: "3.0"
      - key: R_SL
        value: "1.1"
      - key: TP_LEVELS
        value: "3"
      - key: TP_SPLIT
        value: "50,30,20"
      - key: FEE_RATE
        value: "0.001"

      # paper sizing
      - key: POSITION_PCT
        value: "0.05"
      - key: MAX_OPEN_TRADES
        value: "10"
      - key: MIN_USD_PER_TRADE
        value: "10"
      - key: PAPER_START_CASH
        value: "300"
      - key: PAPER_CHECK_SECONDS
        value: "15"

      # feature flags
      - key: EDGE
        value: "1"
      - key: CORR
        value: "1"
      - key: REGIME
        value: "1"
      - key: COOLDOWN
        value: "1"
      - key: SESSION
        value: "1"

      # historical validator
      - key: HIST_LOOKBACK_BARS_5M
        value: "900"
      - key: HIST_MIN_OCCURRENCES
        value: "10"
      - key: HIST_MIN_SUCCESS
        value: "0.55"

      # correlation thresholds
      - key: CORR_BLOCK
        value: "0.8"
      - key: CORR_HALF
        value: "0.6"

      # streak / day guard
      - key: COOLDOWN_LOSSES
        value: "3"
      - key: COOLDOWN_WINDOW_MIN
        value: "120"
      - key: COOLDOWN_PAUSE_MIN
        value: "60"
      - key: DAY_MAX_DD_PCT
        value: "3.0"
      - key: DAY_LOCK_MIN
        value: "180"

      # request hygiene
      - key: RETRY_MAX
        value: "4"
      - key: RETRY_BASE_DELAY
        value: "0.6"
      - key: REQ_JITTER_MIN_MS
        value: "50"
      - key: REQ_JITTER_MAX_MS
        value: "140"
